module.exports = [
  {
    "title": "Click Me",
    "description": "This is the task view, click on the edit icon above to change task details and change status and click on the box above to complete this task. Click on the stopwatch to indicate that you have started the task.",
    "type": "Training",
    "status": "Open",
    "assignee": "",
    "createdBy": "",
    "dateCreated": null,
  },
  {
    "title": "Comment on a task",
    "description": "You can add comments to any tasks by using the comment field below",
    "type": "Training",
    "status": "Open",
    "assignee": "",
    "createdBy": "",
    "dateCreated": null,
  },
  {
    "title": "Add a link to a task",
    "description": "You can add links to any task to attach relevant information to help complete the task. Use the plus icon at the bottom right",
    "type": "Training",
    "status": "Open",
    "assignee": "",
    "createdBy": "",
    "dateCreated": null,
  },
  {
    "title": "Create a new task",
    "description": "Add a new task by clicking the plus icon in the tasks page",
    "type": "Training",
    "status": "Open",
    "assignee": "",
    "createdBy": "",
    "dateCreated": null,
  },
  {
    "title": "Create a new Project",
    "description": "Go to the project page to start a new project and create tasks within the project. They will still be visible to you on the tasks page if they are assigned to you. You can create new tasks within a project and drag and drop them between project stages to change their status.",
    "type": "Training",
    "status": "Open",
    "assignee": "",
    "createdBy": "",
    "dateCreated": null,
  },
  {
    "title": "Update your profile picture",
    "description": "Go to the users tab to edit your account and add a profile picture for you to use.",
    "type": "Training",
    "status": "Open",
    "assignee": "",
    "createdBy": "",
    "dateCreated": null,
  }
];